### PR TITLE
Modifies connection.py to use the proxy password as the elastic servi…

### PR DESCRIPTION
**Pull request by michaelcizmar**
…ce credentials.

Should resolve issue 5

### CODE REVIEW

**Comment by michaelcizmar** [comment]
Bump

**Comment by epugh** [comment]
Hi, I'm working with someone else who has a basic auth enabled Elasticsearch.   They are trying out this proxy, and I asked them to apply this PR to see if it works for them.

**Comment by michaelcizmar** [comment]
They reached out to me in Slack.  I will update the ticket with anything observed from that discussion.

**Comment by smirnoffs** [comment]
Thanks for the contribution @michaelcizmar. And sorry that it took so long.

**Comment by epugh** [comment]
@smirnoffs literally yesterday afternoon @michaelcizmar and I were onstage on a panel in "Innovations in Search" at KMWorld, and @michaelcizmar mentioned "I have a Quepid PR waiting to be merged"...

**Pull request merged**
